# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  super-welcome: circleci/welcome-orb@0.4.1
jobs: 
  one: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/ruby:2.4.1 # specifically, a docker image with ruby 2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
# Steps are a list of commands to run inside the docker container above.
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome01:
    # Run the welcome/run job in its own container
    jobs:
      - one
  welcome02:
    # Run the welcome/run job in its own container
    jobs:
      - super-welcome/run
